- name: Install Ansible Global Configurations
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python

  roles:
    - requirements

